services:
  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - crm-network
    restart: unless-stopped

  frontend:
    image: ghcr.io/jes11sy/dir_crm/frontend:latest
    container_name: crm-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.lead-schem.ru
      - NEXT_PUBLIC_APP_URL=https://lead-schem.ru
      - NEXT_PUBLIC_ENVIRONMENT=production
      - NEXT_PUBLIC_ENABLE_ANALYTICS=true
      - NEXT_PUBLIC_ENABLE_ERROR_REPORTING=true
    networks:
      - crm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    image: ghcr.io/jes11sy/dir_crm/backend:latest
    container_name: crm-backend
    env_file:
      - .env.production
    volumes:
      - ./logs:/var/log/crm
      - ./uploads:/app/uploads
    networks:
      - crm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  crm-network:
    driver: bridge